# Generated by Django 3.2.7 on 2021-09-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='food_preferences',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='Profile.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics', verbose_name='default.jpg'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
